### ISSUE TITLE
Add support for running fluentbit in openshift

### ISSUE THREAD

**Issue by jswoods** [humio/humio-helm-charts#112]
To run fluentbit in openshift, we need to:

1. Add an appropriate SCC so the pod can start
2. Allow fluentbit to run in privileged mode so it can read /var/log on the host
3. Add instructions/docs on how to configure the above

**Comment by brightzheng100** [comment]
Yep, currently this is the workaround that I apply:

```sh
$ oc adm policy add-scc-to-user privileged -z humio-agent-fluentbit-read
$ oc patch DaemonSet humio-agent-fluentbit -p '{"spec":{"template":{"spec":{"containers":[{"name":"humio-agent","securityContext":{"privileged":true}}]}}}}'
```

**Comment by jswoods** [comment]
This has been fixed now in `0.8.25`. One can set the following as per https://docs.humio.com/docs/ingesting-data/log-formats/kubernetes/#helm

```
humio-fluentbit:
  ...
  securityContext:
    privileged: true
  scc:
    enabled: true
 ```
