### ISSUE TITLE
can't set persistence in values.yaml

### ISSUE THREAD

**Issue by Ahmad-Magdy** [humio/humio-helm-charts#12]
In humio-core I wasn't able to set the persistence like size and storageClassName, how i can set the PVC and manage the reference?
In my case, I want to set the PV to be Premium instead of Standard which is a faster type of disk in Azure.

**Comment by jswoods** [comment]
Hi @Ahmad-Magdy. I pushed https://github.com/humio/humio-helm-charts/commit/543b6bde429eeee4255d376cb6e7c1bcd125e196 which should allow you to do this:

```
humio-core:
  storageVolume:
    size: 50Gi
  storageClassName: my-storage-class-name
```

I think we'd like to also manage storage classes with this chart too, which should be coming fairly soon.
