### ISSUE TITLE
getaddrinfo(host='cloud.humio.com:443'): Name or service not known

### ISSUE THREAD

**Issue by gregbird101** [humio/humio-helm-charts#137]
**Situation:** I have followed the instructions to launch the helm chart and I get the below error
**Background:** Followed these instructions [https://library.humio.com/stable/docs/ingesting-data/log-formats/kubernetes/index.html](url)
**Assessment:** It seems that the fluentbit container is unable to resolve DNS however loading up a DNS utils pod in the same namespace it can
**Recommendation:** I have tried IP the cloud humio IP addresses and other enpoint options [https://library.humio.com/reference/endpoints/#endpoints](url)

Any help would be welcome - is it possible to launch the helm chart with the fluentbit debug pod to allow shell or bash?

```
[2022/01/31 09:50:47] [ warn] net_tcp_fd_connect: getaddrinfo(host='cloud.humio.com:443'): Name or service not known
[2022/01/31 09:50:47] [ warn] net_tcp_fd_connect: getaddrinfo(host='cloud.humio.com:443'): Name or service not known
[2022/01/31 09:50:47] [ warn] net_tcp_fd_connect: getaddrinfo(host='cloud.humio.com:443'): Name or service not known
[2022/01/31 09:50:47] [error] [io_tls] flb_io_tls.c:359 NET - Connection was reset by peer
[2022/01/31 09:50:47] [error] [io_tls] flb_io_tls.c:359 NET - Connection was reset by peer
[2022/01/31 09:50:47] [error] [io_tls] flb_io_tls.c:359 NET - Connection was reset by peer
```

Actions:
Setup helm
```
helm repo add humio https://humio.github.io/humio-helm-charts
helm repo update
```
Create file: humio-agent.yml
```
humio-fluentbit:
  enabled: true
  humioHostname: cloud.humio.com:9200
  es:
    tls: true
```

Setup Helm
```
helm install humio humio/humio-helm-charts \
  --namespace cattle-logging \
  --set humio-fluentbit.token=REDACTED \
  --values humio-agent.yml
```
Create DNS utils
```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: it-dev
spec:
  containers:
  - name: dnsutils
    image: k8s.gcr.io/e2e-test-images/jessie-dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  restartPolicy: Always
```
Check all DNS is working
```
kubectl exec -n cattle-logging -i -t dnsutils -- nslookup cloud.humio.com
kubectl exec -n cattle-logging -ti dnsutils -- cat /etc/resolv.conf
kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
kubectl get svc --namespace=kube-system 
kubectl get endpoints kube-dns --namespace=kube-system
```
