### ISSUE TITLE
Kafka and zookeeper configs are confusing

### ISSUE THREAD

**Issue by jswoods** [humio/humio-helm-charts#16]
If we have a config like this:

```
humio-core:
   cp-helm-charts:
     cp-zookeeper:
       servers: 5
     cp-kafka:
       brokers: 5
```

We don't actually use all 5 kafkas/zookeepers. In order to use them, we have to define a separate config like this:

```
humio-core:
   cp-helm-charts:
     cp-zookeeper:
       servers: 5
     cp-kafka:
       brokers: 5
  kafka:
    brokers: 5
  zookeeper:
    servers: 5
```
