### ISSUE TITLE
Ability to configure ingress

### ISSUE THREAD

**Issue by estahn** [humio/humio-helm-charts#17]

**Comment by jswoods** [comment]
Thanks for filing this issue. This is something I'll be working on in the next week or two. Are you using a certificate manager? I was thinking we may want a let's encrypt cert manager as part of this work.

**Comment by estahn** [comment]
Yes, we're using the entire shebang. Ingress/Let's encrypt via cert manager, etc.

The ingress should be fairly open. If you do "helm create test" you will get a scaffold chart already including the ingress.

`values.yaml`
```
ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

`templates/ingress.yaml`
```
{{- if .Values.ingress.enabled -}}
{{- $fullName := include "..fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "..labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
        {{- end }}
  {{- end }}
{{- end }}
```

That should provide a good starting point.
